Support masking of unconnected nodes (LAM)
ecmwf/anemoi-training pull request #171
Opened 2024-11-28 08:33 UTC by JPXKQX

This PR adds support for using masked graphs, resulting in a performance improvement in LAM by dropping unused nodes in the boundary forcing dataset.

## Description
The current release of anemoi-graphs (`0.4.1`) supports dropping unconnected nodes from the limited area graph, with the following code:
```
post_processors:
  - _target_: anemoi.graphs.processors.RemoveUnconnectedNodes
    nodes_name: data
    ignore: cutout_mask # optional
    save_mask_indices_to_attr: indices_connected_nodes # optional
```
`anemoi-graphs` returns the masked graph with an additional node attribute `indices_connected_nodes` (in this example) representing the indices used to mask the input dataset to the new graph `data` nodes.

## Solution

We need to specify these spatial indices in the dataloader config. 
```
grid_indices:
    _target_: anemoi.training.data.grid_indices.MaskedGrid
    nodes_name: data
    node_attribute_name: indices_connected_nodes
```

The performance improvement is of 66 % (from 1,92 it/s to 3,19 it/s) for the 1 GPU default limited area model.

<img width="1093" alt="Screenshot 2024-11-28 at 10 58 06" src="https://github.com/user-attachments/assets/4ecad2c6-5e1a-4037-8b53-6285f91b0cdf">

This PR has been tested successfully on 1 GPU (with `plot: detailed` without `PlotSpectrum` included): 
- [x] Limited Area Model with `reader_group_size=1`
- [x] Stretched grid with `reader_group_size=1`
- [x] Global model with `reader_group_size=1`

This PR has been tested successfully on 2 GPU (with `plot: detailed` without `PlotSpectrum` included): 
- [x] Limited Area Model with `reader_group_size=2`
- [x] Stretched grid with `reader_group_size=2`
- [x] Global model with `reader_group_size=2`

W.I.P.: This mask must be saved to the checkpoint so that it can be used in `anemoi-inference`.

2024-11-28 14:07 UTC, b8raoult submitted a review, later dismissed

2024-12-03 17:12 UTC, JPXKQX commented on src/anemoi/training/data/dataset.py
> +        self.grid_shard_indices = self.grid_indices.get_shard_indices(self.reader_group_rank, self.reader_group_size)
True

2024-12-05 14:15 UTC, theissenhelen commented on src/anemoi/training/data/dataset.py
> +        assert self.reader_group_size >= 1, "reader_group_size must be postive"
change to "positive"

2024-12-05 14:21 UTC, theissenhelen requested changes
Just a typo to fix.

2024-12-05 14:37 UTC, theissenhelen approved these changes
Great work!

2024-12-13 08:36 UTC, merged