Feature/model freezing ❄️
ecmwf/anemoi-training pull request #189
Opened 2024-12-06 10:19 UTC by icedoom888

Solves: #176

2024-12-13 09:36 UTC, JesperDramsch requested changes
Hi @icedoom888! 

Thanks for adding this, I was working on something similar, so might have a refactor coming sometime next year. Until then, I think there are some improvements we should make to the implementation.

1. Pytorch Lightning provides recursive freezing capability.
2. We should make these config entries optional.

Additionally, I had some concerns around unused parameters in the model. During my research I have found some hints that the training strategy may have to be adjusted to still work correctly with unused parameters.

The Pytorch one is here and implements:
https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html#torch.nn.parallel.DistributedDataParallel
`find_unused_parameters`, have you noticed any changes to your (computational) graph as opposed to non-frozen training?

2024-12-13 09:36 UTC, JesperDramsch commented on src/anemoi/training/utils/checkpoint.py
> +        target_name (str): The name of the submodule to freeze.
This is the wrong docstring format. Could you please adjust this to the standard used throughout Anemoi (it's the numpy style).

2024-12-13 09:36 UTC, JesperDramsch commented on src/anemoi/training/config/training/default.yaml
> +submodules_to_freeze: []
This, `transfer_learning`, and future functionality I'm working in regarding fine-tuning, seem to be aligned in there purpose for model loading. I think we should consider not adding too many top-level keys but grouping them in something like `finetuning` or `model_load` or a better name where transfer learning, model loading, freezing, fine-tuning etc can live.

2024-12-17 13:26 UTC, icedoom888 commented on src/anemoi/training/utils/checkpoint.py
> +    for name, child in module.named_children():
I looked into Pytorch Lightning freeze().
The function can only be called on a `LightningModule` class. Most submodules are torch.nn.Module classes.

2024-12-17 13:38 UTC, icedoom888 commented on src/anemoi/training/train/train.py
> +            LOGGER.info("Model initialised from scratch.")
Removed

2024-12-17 14:52 UTC, icedoom888 commented on src/anemoi/training/train/train.py
> +        LOGGER.info("The following submodules will NOT be trained: %s", self.config.training.submodules_to_freeze)
Solved ✅

2025-06-26 09:24 UTC, closed without merging