23 plot a validation sample after long rollout
ecmwf/anemoi-training pull request #26
Opened 2024-08-14 09:19 UTC by sahahner

Solves issue #23 

New callback: For the validation sample, for which we already plot the forecast and forecast errors for the rollout steps used during training, plot the forecasts for selected longer rollouts using the same layout as the plots we already have.

2024-08-15 13:26 UTC, lzampier requested changes
See my suggestions for [CHANGELOG.md](https://github.com/ecmwf/anemoi-training/pull/26/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed) and [src/anemoi/training/diagnostics/callbacks/__init__.py](https://github.com/ecmwf/anemoi-training/pull/26/files#diff-be88bd9789926a500f0714212ab174da8e4d741cf6ef597f23261acbc853dd25) in the specific comments I left.

2024-08-15 13:26 UTC, lzampier commented on src/anemoi/training/diagnostics/callbacks/__init__.py
You could add `@rank_zero_only` and maybe `@abstractmethod` before the `_plot` in line 299, as done in Line 137 within `BasePlotCallback`.

2024-08-21 07:38 UTC, lzampier approved these changes

2024-08-22 15:33 UTC, theissenhelen commented on src/anemoi/training/data/datamodule.py
> +        if self.config.diagnostics.plot.longrollout.enabled:
If both if-statements are enabled, the latter will overwrite the value r, is that intentional?

2024-09-23 15:29 UTC, lzampier approved these changes

2024-09-23 15:31 UTC, lzampier approved these changes

2024-09-23 15:37 UTC, JesperDramsch approved these changes
Approving as proxy for @lzampier

2024-09-23 15:57 UTC, merged