Expanded intro docs and examples
ecmwf/anemoi-training pull request #46
Opened 2024-09-03 09:57 UTC by gareth-j

After working through the documentation to get a simple training run going I encountered some issues with the docs.
This PR:

- fixes some broken links to the other anemoi repos
- updates some text on required overrides in the config
- updates the example config file with what's needed for a run (hopefully)

2024-09-12 19:38 UTC, mchantry commented on docs/start/hydra-intro.rst
> +-  ``hardware.paths.graph``: Location of graph directory
@JPXKQX do you agree it would be best to say "Location to save graphs"?

2024-09-12 19:40 UTC, mchantry commented on docs/user-guide/configuring.rst
> +the graph, here we use `first_graph_m320.pt`.
Should be n320

2024-09-12 19:40 UTC, mchantry commented on docs/user-guide/configuring.rst
> +         graph: first_graph_m320.pt
n320

2024-09-12 19:41 UTC, mchantry requested changes
Once fixed with the typo it looks good-to-go. Thanks for the contribution!

2024-09-17 11:23 UTC, gareth-j commented on docs/user-guide/configuring.rst
> +the graph, here we use `first_graph_m320.pt`.
Done.

2024-09-17 12:07 UTC, mchantry approved these changes
Great, thanks. Please merge @gareth-j .

2024-09-17 12:11 UTC, merged