fix version pinning
ecmwf/anemoi-training pull request #66
Opened 2024-09-27 15:01 UTC by MeraX

relates to https://github.com/ecmwf/anemoi-training/issues/55

2024-09-30 09:35 UTC, JesperDramsch approved these changes
HI @MeraX, thanks for the quick fix!

Merging right away.

2024-09-30 09:38 UTC, JesperDramsch requested changes
> HI @MeraX, thanks for the quick fix!
> 
> Merging right away.

Ah sorry, it looks like the pre-commit hook wasn't run on this and `"anemoi-models>0.3.0",` which should be `"anemoi-models>0.3",`.

I t looks like I can't edit the PR unfortuantely, can you fix this from your side?

2024-09-30 13:07 UTC, FussyDuck commented
[![CLA assistant check](https://bol-claassistant.ecmwf.int:443/pull/badge/not_signed)](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-training?pullRequest=66) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-training?pullRequest=66) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: MeraX<br/>:x: Florian Prill<br/><hr/>**Florian Prill** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/anemoi-training?pullRequest=66) it.</sub>

2024-10-01 09:00 UTC, JesperDramsch approved these changes

2024-10-01 09:02 UTC, merged